### ISSUE TITLE
[Bug]: Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /node_modules/@web3-onboard/react/package.json.

### ISSUE THREAD

**Issue by anuj0361** [blocknative/web3-onboard#1003]
### Current Behavior

While integrating web3-onboard-react package in my Nextjs+typescript project. I am getting runtime error as below

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/Desktop/node_modules/@web3-onboard/react/dist/index.js
require() of ES modules is not supported.
require() of /Users/Desktop/node_modules/@web3-onboard/react/dist/index.js from /Users/Desktop/.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/Desktop/node_modules/@web3-onboard/react/package.json.`

### Expected Behavior

It should run perfectly after doing npm install.

### Steps To Reproduce

Use below package.json & tsconfig file. Do `npm i` & `npm run dev`. You will see above error.

{
  "name": "random",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "nodemon server/index.js --watch server",
    "start": "node server/index.js",
    "build": "next build",
    "lint": "next lint"
  },
  "dependencies": {
    "@apollo/client": "^3.4.13",
    "@bugsnag/js": "^7.9.0",
    "@bugsnag/plugin-react": "^7.9.0",
    "@loadable/component": "^5.15.0",
    "@perp/contract": "2.2.0",
    "@sentry/nextjs": "^6.13.3",
    "@testing-library/jest-dom": "^5.9.0",
    "@testing-library/react": "^10.2.1",
    "@testing-library/user-event": "^12.0.2",
    "@types/jest": "^25.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "@types/sass": "^1.16.1",
    "@uniswap/sdk": "^3.0.3",
    "@walletconnect/web3-provider": "^1.7.1",
    "@web3-onboard/injected-wallets": "^2.0.6",
    "@web3-onboard/react": "^2.1.6",
    "@web3-onboard/walletconnect": "^2.0.1",
    "@web3-react/abstract-connector": "^6.0.7",
    "@web3-react/core": "^6.1.9",
    "@web3-react/injected-connector": "^6.0.7",
    "@web3-react/network-connector": "^6.1.9",
    "@web3-react/walletconnect-connector": "^6.1.9",
    "apollo-link": "^1.2.14",
    "apollo-link-ws": "^1.0.20",
    "autoprefixer": "^10.3.3",
    "axios": "^0.21.1",
    "big.js": "^6.0.3",
    "compression": "^1.7.4",
    "date-and-time": "^2.0.0",
    "dotenv": "^10.0.0",
    "ethers": "^5.5.3",
    "ethers-eip712": "^0.2.0",
    "ethers-multicall": "^0.2.2",
    "express": "^4.17.1",
    "express-validator": "^6.12.2",
    "focus-visible": "^5.2.0",
    "framer-motion": ">=3.0.0",
    "graphql": "^15.6.0",
    "graphql-tag": "^2.12.5",
    "helmet": "^4.6.0",
    "immer": "^8.0.1",
    "jsonwebtoken": "^8.5.1",
    "jwt-decode": "^3.1.2",
    "morgan": "^1.10.0",
    "next": "11.1.0",
    "next-redux-wrapper": "^7.0.5",
    "node-telegram-bot-api": "^0.54.0",
    "postcss": "^8.3.6",
    "postcss-cli": "^8.3.1",
    "rc-tabs": "^11.10.1",
    "react": "17.0.2",
    "react-copy-to-clipboard": "^5.0.4",
    "react-dom": "17.0.2",
    "react-gtm-module": "^2.0.11",
    "react-hot-toast": "^2.1.1",
    "react-hotjar": "^4.0.0",
    "react-lottie": "^1.2.3",
    "react-modal": "^3.14.3",
    "react-redux": "^7.2.6",
    "react-slick": "^0.28.1",
    "react-slider": "^1.3.1",
    "redux": "^4.1.2",
    "redux-devtools-extension": "^2.13.9",
    "redux-thunk": "^2.4.0",
    "sass": "^1.38.1",
    "subscriptions-transport-ws": "^0.9.19",
    "tailwindcss": "^2.2.8",
    "typescript": "4.4.2",
    "unstated-next": "^1.1.0",
    "use-immer": "^0.4.2",
    "web-vitals": "^0.2.2",
    "web3": "^1.7.0",
    "ws": "^8.2.2"
  },
  "devDependencies": {
    "@typechain/ethers-v5": "6.0.5",
    "@types/big.js": "^6.0.2",
    "@types/prettier": "^2.2.2",
    "@types/node": "17.0.9",
    "@types/react": "17.0.38",
    "@types/react-modal": "^3.12.1",
    "@types/react-router-dom": "^5.1.7",
    "@types/react-slick": "^0.23.5",
    "@types/react-slider": "^1.3.1",
    "@types/testing-library__jest-dom": "^5.9.5",
    "@types/yargs": "^16.0.0",
    "eslint": "8.7.0",
    "eslint-config-next": "12.0.8",
    "husky": "^5.1.3",
    "isomorphic-unfetch": "^3.1.0",
    "lint-staged": "^10.5.4",
    "nodemon": "^2.0.13",
    "prettier": "^2.2.1",
    "ts-generator": "^0.1.1",
    "ts-node": "^9.1.1",
    "typechain": "4.0.3",
    "typescript": "4.5.4",
    "typesync": "^0.8.0",
    "yargs": "^16.2.0"
  }
}

tsconfig.json

{
  "compilerOptions": {
    "target": "es5",
    "baseUrl": "src",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src",
    "script"
  ],
  "ts-node": {
    "compilerOptions": {
      "module": "commonjs"
    }
  },
  "exclude": [
    "node_modules"
  ]
}

### Onboard Version

"@web3-onboard/react": "^2.1.6"

### Node Version

v14.17.5

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at eval (webpack-internal:///@web3-onboard/react:1:18)
```

**Comment by anuj0361** [comment]
Closing this issue. Working fine for nextJs version 12 or above.
