### ISSUE TITLE
[Bug]: Binance Support For WalletConnect

### ISSUE THREAD

**Issue by MBA-BG** [blocknative/web3-onboard#1016]
### Current Behavior

My Dapp was working fine with onboard on Ethereum Main/Test nets.

However, while connecting a new Dapp to a Smart Contract on the Binance Smart Chain Main / Test Nets via walletConnect, I get `Internal JSON-RPC error`

I think that might be as you have to send a custom request as per [this](https://docs.binance.org/walletconnect.html)

However, I'm not sure I can send custom requests while using onboard.

### Expected Behavior

Would like the ability to send custom requests or interact with the Binance Smart chain via walletConnect

If it exists, maybe some documentation/clarification on that. 

### Steps To Reproduce

1. Binance Smart Chain (Main/Test)
2. Chrome Browser
3. Metamask Mobile as Mobile Wallet - Android
4. walletConnect
5. 

### Onboard Version

@web3-onboard/walletconnect@2.0.1 --- web3-onboard/react@2.1.2

### Node Version

16.15.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
index.js:1 Error: Internal JSON-RPC error.
    at events.ts:67:1
    at Array.forEach (<anonymous>)
    at EventManager.trigger (events.ts:65:1)
    at WalletConnect._handleIncomingMessages (index.ts:985:1)
```

**Comment by MBA-BG** [comment]
Is working. Must have been something wrong on my end. Sorry for the inconvenience!
