### ISSUE TITLE
[Bug]: Cannot assign to read only property 'chainId' of object '#<l>'

### ISSUE THREAD

**Issue by ChristopherTrimboli** [blocknative/web3-onboard#1197]
### Current Behavior

No code changes, all of a sudden everything is broken and erroring.
Using the React package.

```
Cannot assign to read only property 'chainId' of object '#<l>'
at l._handleChainChanged (inpage.js:1:39117)
at l._handleChainChanged (inpage.js:1:46662)
at l._handleChainChanged (inpage.js:1:44260)
at s.<anonymous> (inpage.js:1:45866)
at i (inpage.js:1:56067)
at s.emit (inpage.js:1:56607)
at inpage.js:1:55131
at d.write [as _write] (inpage.js:1:55154)
at w (inpage.js:17:29867)
at inpage.js:17:33045
at y.write (inpage.js:17:33072)
at i.g (inpage.js:17:22073)
at f (inpage.js:8:21088)
at o.emit (inpage.js:8:24074)
```

### Expected Behavior

Do not error.

### Steps To Reproduce

```
import { init, useConnectWallet } from "@web3-onboard/react";
import injectedModule from "@web3-onboard/injected-wallets";
import magicModule from "@web3-onboard/magic";
import fortmaticModule from "@web3-onboard/fortmatic";
import walletConnectModule from "@web3-onboard/walletconnect";
import coinbaseWalletModule from "@web3-onboard/coinbase";
import gnosisModule from "@web3-onboard/gnosis"
import torusModule from "@web3-onboard/torus"
import ledgerModule from "@web3-onboard/ledger"
import trezorModule from "@web3-onboard/trezor"
import { ethers } from "ethers";
import LunaButton from "./LunaButton";
import { shortenAddress } from "../lib/helpers";
import { useEffect } from "react";

const injected = injectedModule();

const infuraKey = "<INFURA_KEY>"; // TODO: Replace with your own infura key
const rpcUrl = `https://mainnet.infura.io/v3/${infuraKey}`; // TODO: Replace with your own rpc url

const magic = magicModule({ apiKey: "API_KEY" });
const fortmatic = fortmaticModule({ apiKey: "API_KEY" });
const walletConnect = walletConnectModule({
    bridge: "YOUR_CUSTOM_BRIDGE_SERVER",
    qrcodeModalOptions: {
        mobileLinks: ["rainbow", "metamask", "argent", "trust", "imtoken", "pillar"]
    }
});
const coinbaseWalletSdk = coinbaseWalletModule({ darkMode: true });
const gnosis = gnosisModule();
const torus = torusModule();
const ledger = ledgerModule()
const trezor = trezorModule({
    email: '<EMAIL_CONTACT>',
    appUrl: '<APP_URL>'
  })

init({
    wallets: [
        injected,
        magic,
        fortmatic,
        walletConnect,
        coinbaseWalletSdk,
        gnosis,
        torus,
        ledger,
        trezor
    ],
    chains: [
        {
            id: "0x1",
            token: "ETH",
            label: "Ethereum Mainnet",
            rpcUrl
        }
    ],
    appMetadata: {
        name: "abc",
        description: "abc"
    },
    accountCenter: {
        desktop: {
            containerElement: "div",
            enabled: false
        },
        mobile: {
            containerElement: "div",
            enabled: false
        }
    }
});

const Web3Onboard = () => {
    const [{ wallet, connecting }, connect, disconnect] = useConnectWallet();

    useEffect(() => {
        if (wallet) {
            const ethersProvider = new ethers.providers.Web3Provider(wallet.provider, "any");
            console.log("ethersProvider:", ethersProvider);
            console.log("wallet:", wallet);
        }
    }, [wallet])

    return <div>
        <LunaButton
            onClick={() => (wallet ? disconnect(wallet) : connect())}
        >
            {connecting ? "Connecting..." : wallet ? `${shortenAddress(wallet?.accounts?.[0]?.address, 12)}` : "Connect"}
        </LunaButton>
    </div>
}

export default Web3Onboard;
```

### What package is effected by this issue?

@web3-onboard/react

### Is this a build or a runtime issue?

Runtime

### Package Version

2.2.5

### Node Version

16.15.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught TypeError: Cannot assign to read only property 'chainId' of object '#<l>'
    at l._handleChainChanged (inpage.js:1:39117)
    at l._handleChainChanged (inpage.js:1:46662)
    at l._handleChainChanged (inpage.js:1:44260)
    at s.<anonymous> (inpage.js:1:45866)
    at i (inpage.js:1:56067)
    at s.emit (inpage.js:1:56607)
    at inpage.js:1:55131
    at d.write [as _write] (inpage.js:1:55154)
    at w (inpage.js:17:29867)
    at inpage.js:17:33045
    at y.write (inpage.js:17:33072)
    at i.g (inpage.js:17:22073)
    at f (inpage.js:8:21088)
    at o.emit (inpage.js:8:24074)
    at _ (inpage.js:17:16876)
    at v (inpage.js:17:16691)
    at w.push (inpage.js:17:17502)
    at l._write (inpage.js:1:3002)
    at w (inpage.js:17:29867)
    at inpage.js:17:33045
    at y.write (inpage.js:17:33072)
    at i.g (inpage.js:1:16642)
    at f (inpage.js:8:21088)
    at o.emit (inpage.js:8:24074)
    at _ (inpage.js:1:11481)
    at v (inpage.js:1:11296)
    at w.push (inpage.js:1:12107)
    at i._onData (inpage.js:1:3987)
    at i._onMessage (inpage.js:1:5026)
_handleChainChanged @ inpage.js:1
_handleChainChanged @ inpage.js:1
_handleChainChanged @ inpage.js:1
(anonymous) @ inpage.js:1
i @ inpage.js:1
emit @ inpage.js:1
(anonymous) @ inpage.js:1
write @ inpage.js:1
w @ inpage.js:17
(anonymous) @ inpage.js:17
y.write @ inpage.js:17
g @ inpage.js:17
f @ inpage.js:8
o.emit @ inpage.js:8
_ @ inpage.js:17
v @ inpage.js:17
w.push @ inpage.js:17
_write @ inpage.js:1
w @ inpage.js:17
(anonymous) @ inpage.js:17
y.write @ inpage.js:17
g @ inpage.js:1
f @ inpage.js:8
o.emit @ inpage.js:8
_ @ inpage.js:1
v @ inpage.js:1
w.push @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
setTimeout (async)
i @ inpage.js:1
emit @ inpage.js:1
(anonymous) @ inpage.js:1
write @ inpage.js:1
w @ inpage.js:17
(anonymous) @ inpage.js:17
y.write @ inpage.js:17
g @ inpage.js:17
f @ inpage.js:8
o.emit @ inpage.js:8
_ @ inpage.js:17
v @ inpage.js:17
w.push @ inpage.js:17
_write @ inpage.js:1
w @ inpage.js:17
(anonymous) @ inpage.js:17
y.write @ inpage.js:17
g @ inpage.js:1
f @ inpage.js:8
o.emit @ inpage.js:8
_ @ inpage.js:1
v @ inpage.js:1
w.push @ inpage.js:1
_onData @ inpage.js:1
_onMessage @ inpage.js:1
postMessage (async)
_postMessage @ contentscript.js:1
_write @ contentscript.js:1
w @ contentscript.js:1
(anonymous) @ contentscript.js:1
y.write @ contentscript.js:1
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_write @ contentscript.js:17
w @ contentscript.js:17
(anonymous) @ contentscript.js:17
y.write @ contentscript.js:17
g @ contentscript.js:17
d @ contentscript.js:8
o.emit @ contentscript.js:8
_ @ contentscript.js:17
v @ contentscript.js:17
w.push @ contentscript.js:17
_onMessage @ contentscript.js:8
(anonymous) @ contentscript.js:8
Show 33 more frames
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@ChristopherTrimboli looking into this now. Few questions...
Which version did you upgrade from?
A note on `appMetaData` if being used an `icon` is required.
I found after removing the `containerElement` that the application works as expected. Is this property required in your application?

**Comment by ChristopherTrimboli** [comment]
I actually did have `icon` in there but removed for client info censorship... interesting find on `containerElement`. 
I removed `containerElement` but still have same issue, I also tried removing the whole `accountCenter` object, to let it act by default, still same issue.

Note: I am using Next.js server side React.

**Comment by 0xadsyst** [comment]
Just wanted to add to this, I'm also using Next.js, a new project built from a template, I was getting the same error (I'm new to front end, so figured I was doing something wrong), so I tried web3-react and got the same error. 
Then I tried Chrome instead of Brave and didn't get the error on either web3-react or web3-onboard.
Hope this helps in some way.

**Comment by ChristopherTrimboli** [comment]
> Just wanted to add to this, I'm also using Next.js, a new project built from a template, I was getting the same error (I'm new to front end, so figured I was doing something wrong), so I tried web3-react and got the same error. Then I tried Chrome instead of Brave and didn't get the error on either web3-react or web3-onboard. Hope this helps in some way.

Tried Edge browser, can confirm, not seeing my issue in Edge. 
I tried de-activating the Brave Browser ad-blocker shields and also my AdBlocker + Ublock extensions in Chrome... no luck, still get the same error.
Edge running perfect lol

**Comment by taylorjdawson** [comment]
@ChristopherTrimboli @0xadsyst Thanks for the additional information -- we'll continue to investigate this on our end 👍🏾

**Comment by ChristopherTrimboli** [comment]
> @ChristopherTrimboli @0xadsyst Thanks for the additional information -- we'll continue to investigate this on our end 👍🏾

On further investigation... I removed web3-onboard completely from our project... still have the error.
It seems to be a Metamask + Brave Browser bug.
Apologies for the time waster.

**Comment by taylorjdawson** [comment]
@ChristopherTrimboli Excellent that is good to hear! If you by chance discover the issue would you mind posting the solution here just in case someone ends up with the same error in the future, thanks!

**Comment by ChristopherTrimboli** [comment]
this is the real bug in Metamask: https://github.com/MetaMask/metamask-extension/issues/15479
