### ISSUE TITLE
Properly managing state with React / web3-onboard: I've been stuck on this for days

### ISSUE THREAD

**Issue by Brentably** [blocknative/web3-onboard#1404]
The way I'm approaching this is that I am calculating my provider from ethers, once, then storing it in a global state object.
That means that every time [wallet] updates from web3-onboard, I need to update my global state object.

So the way I approached this initially is that I had a useEffect hook with a [wallet] dependency running.
That caused an infinite loop.
So now I have a useEffect running with no dependency [] and am using the subscribe API.
Unfortunately it still causes an infinitely loop.

And when I try to properly unsubscribe from updates by returning () => unsubscribe() from my useEffect hook, 
I get this error:

Subscriber.ts:111 Uncaught TypeError: Cannot read properties of undefined (reading 'closed')
    at Subscriber.unsubscribe (Subscriber.ts:111:1)
    at cleanup (App.tsx:94:1)
    at safelyCallDestroy (react-dom.development.js:22932:1)
    at commitHookEffectListUnmount (react-dom.development.js:23100:1)
    at invokePassiveEffectUnmountInDEV (react-dom.development.js:25207:1)
    at invokeEffectsInDev (react-dom.development.js:27351:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27324:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27056:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at react-dom.development.js:26769:1

My repo is at [https://github.com/Brentably/summon-lend-frontend](https://github.com/Brentably/summon-lend-frontend).
Although I've tried many things other than what is pushed here.

Anything helps, and I'm happy to answer any questions, but what would be most useful are links to react repo's that use web3-onboard, so I can understand how to properly implement it. 

Thanks.

**Comment by Brentably** [comment]
Yeah I noticed that it only happens with wallet connect. Wondering if that's because of the way @web3-onboard/walletconnect works or because of the new Wallet Connect V2.... :/

**Comment by Brentably** [comment]
Yeah I can't get the React demo repo to run either... hmm
