### ISSUE TITLE
Cannot read properties of undefined (reading 'secondaryTokens')

### ISSUE THREAD

**Issue by LFerronato** [blocknative/web3-onboard#1746]
### Current Behavior

Hey guys, 
Can u help me understand how to resolve this issue.

I'm monitoring my app with Sentry, and I am seeing that some users of the site are having this console.error in the terminal.

```
TypeError: Cannot read properties of undefined (reading 'secondaryTokens')
```

at Sentry report, i see that comes from:
![image](https://github.com/blocknative/web3-onboard/assets/43012047/fad53694-5519-409d-ac46-c84738d0a535)

It may be that there are no major problems, but I would like to treat this to avoid any side effects.

Ps.: 

### Expected Behavior

errors like "read properties of undefined" aren't very cool, and it seems to be something that wasn't handled on purpose, so it would be good to see if there are any points of improvement.

### Steps To Reproduce

I confess I don't know.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.18.0

### Node Version

18.x

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'secondaryTokens')
  at updateAccountDetails(./node_modules/.pnpm/@web3-onboard+core@2.18.0/node_modules/@web3-onboard/core/dist/index-89f66b35.js:7895:1)
  at next(./node_modules/.pnpm/@web3-onboard+core@2.18.0/node_modules/@web3-onboard/core/dist/index-89f66b35.js:7943:1)
  at ConsumerObserver.prototype.next(./node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm5/internal/Subscriber.js:96:1)
  at Subscriber.prototype._next(./node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm5/internal/Subscriber.js:63:1)
  at Subscriber.prototype.next(./node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm5/internal/Subscriber.js:34:1)
  at cb(./node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm5/internal/Subject.js:41:1)
  at errorContext(./node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm5/internal/util/errorContext.js:19:1)
  at Subject.prototype.next(./node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm5/internal/Subject.js:31:9)
  at BehaviorSubject.prototype.next(./node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/esm5/internal/BehaviorSubject.js:31:1)
  at setStep(./node_modules/.pnpm/@web3-onboard+core@2.18.0/node_modules/@web3-onboard/core/dist/index-89f66b35.js:7951:1)
  at connectWallet(./node_modules/.pnpm/@web3-onboard+core@2.18.0/node_modules/@web3-onboard/core/dist/index-89f66b35.js:7840:1)
```

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
This is solved in the latest versions of core/react/vue - closing as this issue has been handled. Please feel free to continue the conversation or discussion if there is still an issue. Thanks!
