### ISSUE TITLE
Walletconnect not working with Metamask mobile app

### ISSUE THREAD

**Issue by anuj0361** [blocknative/web3-onboard#1815]
### Current Behavior

I should be able to connect using Wallet connect QR code modal through Metamask mobile app.

### Expected Behavior

Walletconnect not working with Metamask mobile app

### Steps To Reproduce

1. Open https://oliveapp.finance/earn/vaults
2. Click Connect Wallet & Choose Wallet connect option
3. QR code will popup
4. Scan this QR code from your Metamask Mobile app.
5. It will through error

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Runtime

### Package Version

2.8.8

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
`8776.5a17a94aa453920a.js:85 Error: User rejected methods.
    at 8776.5a17a94aa453920a.js:33:31191
    at async n (8776.5a17a94aa453920a.js:33:31018)
_app-7dd9a326e04a4a14.js:5 err creating new session:  Error: User rejected methods.
    at 8776.5a17a94aa453920a.js:33:31191
    at async n (8776.5a17a94aa453920a.js:33:31018)`
```

### Anything else?

Versions
    "@web3-onboard/injected-wallets": "^2.10.1",
    "@web3-onboard/react": "^2.8.8",
    "@web3-onboard/walletconnect": "^2.4.0",

<img width="455" alt="image" src="https://github.com/blocknative/web3-onboard/assets/17145736/7c5f5fbf-19c1-4b35-b163-8a471243b9ed">
Using this config for wallet connect

### Sanity Check

- [X] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Adamj1232** [comment]
@anuj0361 we are aware of the issue and working closely with the walletconnect and MetaMask teams to try and resolve this issue. We will report here as progress is made.

**Comment by anuj0361** [comment]
If there's an ETA please share. @Adamj1232

**Comment by chouandy** [comment]
Hi @Adamj1232,
I found that the possible problem is when appMetadata doesn't set `explore` or `gettingStartedGuide` url.
This [`url`](https://github.com/blocknative/web3-onboard/blob/develop/packages/walletconnect/src/v2.ts#L61) has an empty string.
The MetaMask mobile wallet should have verified that this `url` is not empty, resulting in an error.
After setting the explorer url everything works fine.
.

**Comment by 0xhashmap** [comment]
I can confirm that the problem is not present after adding an `explore` url string in the `appMetadata` object.

**Comment by Adamj1232** [comment]
Confirming @0xhashmap  - @chouandy @anuj0361  - Please add an `explore` URL to the onboard initialization's `appMetaData` object.
MetaMask added a requirement that a URL is passed with WalletConnect support and the `appMetaData.explorer` is passed into walletConnect v2 initialization.
I will get a PR together to add the requirement to the TS object and all docs.
Thank you for the feedback and community support!

**Comment by Adamj1232** [comment]
There is a PR open - https://github.com/blocknative/web3-onboard/pull/1822 to add a WC init prop to define this more clearly as well as enhanced validation and documentation around this.
To resolve this issue in the short term please pass in the dapp URL into web3OnboardInit.appMetaData.explorer or you can wait until the noted PR is in alpha to test with the walletconnect init prop dappUrl
