### ISSUE TITLE
Error in production but not in development

### ISSUE THREAD

**Issue by cryptobredda** [blocknative/web3-onboard#1819]
### Current Behavior

Hello guys, How you all doing? hope you all are doing great. 

I have been running into this issue for the past week and I am trying to figure out a solution for it. 

I am using web3-onboard as my main wallet connector and it works completely find on development but when I push my project to production I get all sort of errors. 

currently i am struggling with this error:

```

TypeError: Cannot read properties of undefined (reading 'version')
    at walletConnect (file:///vercel/path0/node_modules/@web3-onboard/walletconnect/dist/index.js:10:31)
    at /vercel/path0/.next/server/pages/_app.js:1522:94
> Build error occurred
Error: Failed to collect page data for /
    at /vercel/path0/node_modules/next/dist/build/utils.js:959:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'

```

It happens for all pages and I cant seem to get it going away.

Next error I got is on the frontend when I try to connect to the website:

```
main-1a2cd11733cdaa06.js:1 TypeError: Cannot read properties of undefined (reading 'context')

main-1a2cd11733cdaa06.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

main-1a2cd11733cdaa06.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getInitialProps')
```

This error was the first error I got when I pushed my project, I dont get this error on my development environment but when I push to production I get it. I tried playing around and I got the other error but still no luck getting the wallet connector to work on production.

My setup is:

Next js 13.0.3
React: 18.2.0
Fails on Vercel deployment and AWS 
Ethers: 5.7.2

not sure what other stuff I need to share.

Note:
I have succesfuully deployed this wallet connector before with Next 12 but with Next 13 I am having issues on production.

### What package is effected by this issue?

@web3-onboard/core

### Is this a build or a runtime issue?

Build, Runtime

### Package Version

2.20.2

### Node Version

16.18

### Sanity Check

- [ ] If this is a build issue, I have included my build config. If this is a runtime issue, I have included reproduction steps and/or a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by leightkt** [comment]
Have you upgraded to the most recent version of @web3-onboard/walletconnect? 
WalletConnect recently depreciated V1 and the team had to make some changes to the package

**Comment by leightkt** [comment]
@cryptobredda is this still an issue for you after upgrading to the latest packages?

**Comment by leightkt** [comment]
Closing due to inactivity. Please feel free to reopen with additional comments.
